services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: "admin123"
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native client port
      - "9009:9009"   # TCP ingestion (optional)
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: metabase-postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase_pass
      POSTGRES_DB: metabase
    ports:
      - "5432:5432"  # host:container
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: postgres
      MB_DB_PORT: 5432         # ← must be the **container** port, not 54322
      MB_DB_DBNAME: metabase
      MB_DB_USER: metabase
      MB_DB_PASS: metabase_pass
    volumes:
      - metabase_data:/metabase-data
    restart: unless-stopped

volumes:
  clickhouse_data:
  pg_data:
  metabase_data:
