CREATE TABLE obd_injected_faults (
    user_id UUID,
    timestamp DateTime,
    
    ENGINE_RUN_TIME Float32,
    ENGINE_RPM Float32,
    VEHICLE_SPEED Float32,
    THROTTLE Float32,
    ENGINE_LOAD Float32,
    COOLANT_TEMPERATURE Float32,

    LONG_TERM_FUEL_TRIM_BANK_1 Float32,
    SHORT_TERM_FUEL_TRIM_BANK_1 Float32,
    INTAKE_MANIFOLD_PRESSURE Float32,
    FUEL_TANK Float32,
    ABSOLUTE_THROTTLE_B Float32,
    PEDAL_D Float32,
    PEDAL_E Float32,
    COMMANDED_THROTTLE_ACTUATOR Float32,
    FUEL_AIR_COMMANDED_EQUIV_RATIO Float32,

    ABSOLUTE_BAROMETRIC_PRESSURE Float32,
    RELATIVE_THROTTLE_POSITION Float32,
    INTAKE_AIR_TEMP Float32,
    TIMING_ADVANCE Float32,

    CATALYST_TEMPERATURE_BANK1_SENSOR1 Float32,
    CATALYST_TEMPERATURE_BANK1_SENSOR2 Float32,
    CONTROL_MODULE_VOLTAGE Float32,
    COMMANDED_EVAPORATIVE_PURGE Float32,

    TIME_RUN_WITH_MIL_ON Float32,
    TIME_SINCE_TROUBLE_CODES_CLEARED Float32,
    DISTANCE_TRAVELED_WITH_MIL_ON Float32,
    WARM_UPS_SINCE_CODES_CLEARED Float32,

    injected_fault_type String,
    is_synthetic UInt8
)
ENGINE = MergeTree
ORDER BY (user_id, timestamp);
