CREATE OR REPLACE VIEW obd_all_faults AS

-- Clean data block
SELECT
    user_id,
    timestamp,
    ENGINE_RUN_TIME,
    ENGINE_RPM,
    VEHICLE_SPEED,
    THROTTLE,
    ENGINE_LOAD,
    COOLANT_TEMPERATURE,
    LONG_TERM_FUEL_TRIM_BANK_1,
    SHORT_TERM_FUEL_TRIM_BANK_1,
    INTAKE_MANIFOLD_PRESSURE,
    FUEL_TANK,
    ABSOLUTE_THROTTLE_B,
    PEDAL_D,
    PEDAL_E,
    COMMANDED_THROTTLE_ACTUATOR,
    FUEL_AIR_COMMANDED_EQUIV_RATIO,
    ABSOLUTE_BAROMETRIC_PRESSURE,
    RELATIVE_THROTTLE_POSITION,
    INTAKE_AIR_TEMP,
    TIMING_ADVANCE,
    CATALYST_TEMPERATURE_BANK1_SENSOR1,
    CATALYST_TEMPERATURE_BANK1_SENSOR2,
    CONTROL_MODULE_VOLTAGE,
    COMMANDED_EVAPORATIVE_PURGE,
    TIME_RUN_WITH_MIL_ON,
    TIME_SINCE_TROUBLE_CODES_CLEARED,
    DISTANCE_TRAVELED_WITH_MIL_ON,
    WARM_UPS_SINCE_CODES_CLEARED,
    CAST(NULL AS Nullable(String)) AS injected_fault_type,
    CAST(NULL AS Nullable(UInt8)) AS is_synthetic,
    'clean' AS source,
    -- Fault detection logic
    IF(COOLANT_TEMPERATURE > 120, 'Overheating',
    IF(CONTROL_MODULE_VOLTAGE < 11, 'Low Voltage',
    IF(PEDAL_D > 50 AND THROTTLE < 15, 'Throttle Lag',
    IF(INTAKE_MANIFOLD_PRESSURE > 55 AND LONG_TERM_FUEL_TRIM_BANK_1 > 20, 'Vacuum Leak',
    NULL)))) AS detected_fault

FROM obd_clean_data

UNION ALL

-- Injected fault block
SELECT
    user_id,
    timestamp,
    ENGINE_RUN_TIME,
    ENGINE_RPM,
    VEHICLE_SPEED,
    THROTTLE,
    ENGINE_LOAD,
    COOLANT_TEMPERATURE,
    LONG_TERM_FUEL_TRIM_BANK_1,
    SHORT_TERM_FUEL_TRIM_BANK_1,
    INTAKE_MANIFOLD_PRESSURE,
    FUEL_TANK,
    ABSOLUTE_THROTTLE_B,
    PEDAL_D,
    PEDAL_E,
    COMMANDED_THROTTLE_ACTUATOR,
    FUEL_AIR_COMMANDED_EQUIV_RATIO,
    ABSOLUTE_BAROMETRIC_PRESSURE,
    RELATIVE_THROTTLE_POSITION,
    INTAKE_AIR_TEMP,
    TIMING_ADVANCE,
    CATALYST_TEMPERATURE_BANK1_SENSOR1,
    CATALYST_TEMPERATURE_BANK1_SENSOR2,
    CONTROL_MODULE_VOLTAGE,
    COMMANDED_EVAPORATIVE_PURGE,
    TIME_RUN_WITH_MIL_ON,
    TIME_SINCE_TROUBLE_CODES_CLEARED,
    DISTANCE_TRAVELED_WITH_MIL_ON,
    WARM_UPS_SINCE_CODES_CLEARED,
    injected_fault_type,
    is_synthetic,
    'injected' AS source,
    -- Fault detection logic
    IF(COOLANT_TEMPERATURE > 120, 'Overheating',
    IF(CONTROL_MODULE_VOLTAGE < 11, 'Low Voltage',
    IF(PEDAL_D > 50 AND THROTTLE < 15, 'Throttle Lag',
    IF(INTAKE_MANIFOLD_PRESSURE > 55 AND LONG_TERM_FUEL_TRIM_BANK_1 > 20, 'Vacuum Leak',
    NULL)))) AS detected_fault

FROM obd_injected_faults;
